#!/bin/sh
VERSION="`basename $0` v1.0 - 20211123"
help() {
    cat <<EOD
Usage: `basename $0` [OPTION]
   OPTIONS
   -------
   --help|-h                          Display this help
   --osrel|-o <release>               OS release from which to build
                                      current: $OS_REL
   --platform|-P <platform>           Build platform
                                      current: $BUILD_PLATF
   --prefix|-p <path>                 Install prefix
                                      current: $PREFIX
   --revision|-r <rev>                Build revision number
                                      current: 1
   --trial|-t                         Trial run
   --version|-v <version>             Singularity version to build
                                      current: $SINGULARITY_VER

$VERSION
Alessandro De Salvo <Alessandro.DeSalvo@roma1.infn.it>
EOD
}

# Defaults
SINGULARITY_VER="3.8.4"
SINGULARITY_REV=1
OS_REL=fc35
CDIR=$PWD
ARCH="`uname -m`"
BUILD_PLATF="`/bin/cat /build-platform`"

OPTS=`getopt -o ho:p:r:tv: -l help,osrel:,platform:,revision:,trial,version: -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..."; exit -1 ; fi
eval set -- "$OPTS"

while true ; do
    case "$1" in
        --help|-h)        help;exit;;
        --osrel|-o)       OS_REL="$2";shift 2;;
        --platform|-P)    BUILD_PLATF="$2";shift 2;;
        --prefix|-p)      PREFIX="$2";shift 2;;
        --revision|-r)    SINGULARITY_REV="$2";shift 2;;
        --trial|-t)       TRIAL="y";shift;;
        --version|-v)     SINGULARITY_VER="$2";shift 2;;
        --)               shift;break;;
        \?)               break;
        exit;;
    esac
done

[ -z "$PREFIX" ] && PREFIX=/cvmfs/atlas.cern.ch/repo/containers/sw/singularity/${ARCH}-${BUILD_PLATF}/${SINGULARITY_VER}
[ "$SINGULARITY_REV" != "1" ] && PREFIX=${PREFIX}-${SINGULARITY_REV}
rpm -Uhv https://kojipkgs.fedoraproject.org/packages/singularity/${SINGULARITY_VER}/${SINGULARITY_REV}.${OS_REL}/src/singularity-${SINGULARITY_VER}-${SINGULARITY_REV}.${OS_REL}.src.rpm
cat > ~/.rpmmacros <<EOD
%_prefix $PREFIX
%_sysconfdir ${PREFIX}/etc
%_localstatedir ${PREFIX}/var
EOD

cd ~/rpmbuild/SPECS
sed -i '/libseccomp-devel/ s/^#*/#/' singularity.spec
rpmbuild -ba singularity.spec
echo Installing singularity-${SINGULARITY_VER}-${SINGULARITY_REV}*.${ARCH}.rpm
[ -s ~/rpmbuild/RPMS/${ARCH}/singularity-runtime-${SINGULARITY_VER}-${SINGULARITY_REV}*.${ARCH}.rpm ] && SINGULARITY_DEPS=~/rpmbuild/RPMS/${ARCH}/singularity-runtime-${SINGULARITY_VER}-${SINGULARITY_REV}*.${ARCH}.rpm
rpm -Uhv ~/rpmbuild/RPMS/${ARCH}/singularity-${SINGULARITY_VER}-${SINGULARITY_REV}*.${ARCH}.rpm $SINGULARITY_DEPS
cd `dirname $PREFIX`
rm -f ${PREFIX}/libexec/singularity/bin/starter-suid
echo Creating tarball /root/singularity-${SINGULARITY_VER}-${SINGULARITY_REV}.tar.gz
tar cfz /root/singularity-${SINGULARITY_VER}-${SINGULARITY_REV}.tar.gz `basename ${PREFIX}`
cd $CDIR
exit
