#!/bin/sh
VERSION="`basename $0` v1.0 - 20211123"
help() {
    cat <<EOD
Usage: `basename $0` [OPTION]
   OPTIONS
   -------
   --help|-h                          Display this help
   --osrel|-o <release>               OS release from which to build
                                      current: $OS_REL
   --platform|-P <platform>           Build platform
                                      current: $BUILD_PLATF
   --prefix|-p <path>                 Install prefix
                                      current: $PREFIX
   --revision|-r <rev>                Build revision number
                                      current: 1
   --trial|-t                         Trial run
   --version|-v <version>             Singularity version to build
                                      current: $APPTAINER_VER

$VERSION
Alessandro De Salvo <Alessandro.DeSalvo@roma1.infn.it>
EOD
}

# Defaults
APPTAINER_VER="1.0.0"
APPTAINER_REV=1
OS_REL=fc37
CDIR=$PWD
ARCH="`uname -m`"
BUILD_PLATF="`/bin/cat /build-platform`"

OPTS=`getopt -o ho:p:r:tv: -l help,osrel:,platform:,revision:,trial,version: -- "$@"`
if [ $? != 0 ] ; then echo "Terminating..."; exit -1 ; fi
eval set -- "$OPTS"

while true ; do
    case "$1" in
        --help|-h)        help;exit;;
        --osrel|-o)       OS_REL="$2";shift 2;;
        --platform|-P)    BUILD_PLATF="$2";shift 2;;
        --prefix|-p)      PREFIX="$2";shift 2;;
        --revision|-r)    APPTAINER_REV="$2";shift 2;;
        --trial|-t)       TRIAL="y";shift;;
        --version|-v)     APPTAINER_VER="$2";shift 2;;
        --)               shift;break;;
        \?)               break;
        exit;;
    esac
done

[ -z "$PREFIX" ] && PREFIX=/cvmfs/atlas.cern.ch/repo/containers/sw/apptainer/${ARCH}-${BUILD_PLATF}/${APPTAINER_VER}
[ "$APPTAINER_REV" != "1" ] && PREFIX=${PREFIX}-${APPTAINER_REV}
rpm -Uhv https://kojipkgs.fedoraproject.org/packages/apptainer/${APPTAINER_VER}/${APPTAINER_REV}.${OS_REL}/src/apptainer-${APPTAINER_VER}-${APPTAINER_REV}.${OS_REL}.src.rpm
cat > ~/.rpmmacros <<EOD
%_prefix $PREFIX
%_sysconfdir ${PREFIX}/etc
%_localstatedir ${PREFIX}/var
%_sharedstatedir ${PREFIX}/var/lib
EOD

cd ~/rpmbuild/SPECS
sed -i '/libseccomp-devel/ s/^#*/#/' apptainer.spec
rpmbuild -ba apptainer.spec
echo Installing apptainer-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm
[ -s ~/rpmbuild/RPMS/${ARCH}/apptainer-runtime-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm ] && APPTAINER_DEPS=~/rpmbuild/RPMS/${ARCH}/apptainer-runtime-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm
[ -s ~/rpmbuild/RPMS/${ARCH}/apptainer-suid-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm ] && APPTAINER_DEPS="$APPTAINER_DEPS ~/rpmbuild/RPMS/${ARCH}/apptainer-suid-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm"
rpm -Uhv ~/rpmbuild/RPMS/${ARCH}/apptainer-${APPTAINER_VER}-${APPTAINER_REV}*.${ARCH}.rpm $APPTAINER_DEPS
cd `dirname $PREFIX`
rm -f ${PREFIX}/libexec/apptainer/bin/starter-suid
echo Creating tarball /root/apptainer-${APPTAINER_VER}-${APPTAINER_REV}-${ARCH}.${BUILD_PLATF}.tar.gz
tar cfz /root/apptainer-${APPTAINER_VER}-${APPTAINER_REV}-${ARCH}.${BUILD_PLATF}.tar.gz `basename ${PREFIX}`
cd $CDIR
exit
